/*
 * File: app/view/TasksViewModel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskList.view.TasksViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.tasks',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.writer.Json'
    ],

    stores: {
        controleEPIs: {
            pageSize: 100,
            autoLoad: true,
            model: 'TaskList.model.ControleEPI',
            proxy: {
                type: 'ajax',
                api: {
                    create: 'php/criaCadastroEPI.php',
                    read: 'php/listaControleEPI.php',
                    update: 'php/atualizaCadastroEPI.php',
                    destroy: 'php/deletaCadastroEPI.php'
                },
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                },
                writer: {
                    type: 'json',
                    encode: true,
                    rootProperty: 'data'
                }
            }
        }
    }

});