/*
 * File: app/view/Tasks.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskList.view.Tasks', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.tasks',

    requires: [
        'TaskList.view.TasksViewModel',
        'TaskList.view.TasksViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.form.field.Display',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.button.Button',
        'Ext.toolbar.Toolbar'
    ],

    controller: 'tasks',
    viewModel: {
        type: 'tasks'
    },
    layout: 'fit',

    items: [
        {
            xtype: 'panel',
            layout: 'border',
            collapsed: false,
            title: 'Controle de Entrega de EPI',
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    region: 'center',
                    split: true,
                    reference: 'list',
                    resizable: false,
                    title: '',
                    forceFit: true,
                    bind: {
                        store: '{controleEPIs}'
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'ID',
                            text: 'ID'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'RE',
                            text: 'RE'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Colaborador',
                            text: 'Colaborador'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Cargo',
                            text: 'Cargo'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Setor',
                            text: 'Setor'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'EPI',
                            text: 'EPI'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Data',
                            text: 'Data'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'Responsavel',
                            text: 'Responsavel'
                        }
                    ],
                    listeners: {
                        select: 'select'
                    }
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    region: 'east',
                    split: true,
                    reference: 'display',
                    width: 150,
                    layout: 'card',
                    bodyBorder: true,
                    items: [
                        {
                            xtype: 'panel',
                            reference: 'selectMessage',
                            bodyBorder: true,
                            layout: {
                                type: 'vbox',
                                align: 'center',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    flex: 1,
                                    html: '<h1>Selecione Um Registro</h1>'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            reference: 'details',
                            bodyBorder: true,
                            bodyPadding: 10,
                            items: [
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'ID',
                                    name: 'ID',
                                    bind: {
                                        value: '{record.ID}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'RE',
                                    name: '',
                                    bind: {
                                        value: '{record.RE}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Colaborador',
                                    bind: {
                                        value: '{record.Colaborador}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Cargo',
                                    bind: {
                                        value: '{record.Cargo}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Setor',
                                    bind: {
                                        value: '{record.Setor}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'EPI',
                                    bind: {
                                        value: '{record.EPI}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Data',
                                    bind: {
                                        value: '{record.Data}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Responsavel',
                                    bind: {
                                        value: '{record.Responsavel}'
                                    }
                                },
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Hora do Cadastro',
                                    bind: {
                                        value: '{record.stamp}'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            reference: 'form',
                            bodyBorder: true,
                            bodyPadding: 10,
                            title: 'Edit Task',
                            items: [
                                {
                                    xtype: 'textfield',
                                    width: 252,
                                    fieldLabel: 'RE',
                                    name: 'RE',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    width: 315,
                                    fieldLabel: 'Colaborador',
                                    name: 'Colaborador',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    width: 315,
                                    fieldLabel: 'Cargo',
                                    name: 'Cargo',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    width: 315,
                                    fieldLabel: 'Setor',
                                    name: 'Setor',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    width: 315,
                                    fieldLabel: 'EPI',
                                    name: 'EPI',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'datefield',
                                    width: 252,
                                    fieldLabel: 'Data',
                                    name: 'Data',
                                    allowBlank: false,
                                    format: 'd/m/Y'
                                },
                                {
                                    xtype: 'textfield',
                                    width: 252,
                                    fieldLabel: 'Responsavel Pela Entrega',
                                    name: 'Responsavel',
                                    allowBlank: false,
                                    maxLength: 30,
                                    minLength: 5
                                },
                                {
                                    xtype: 'container',
                                    padding: 10,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            formBind: true,
                                            itemId: 'saveButton',
                                            margin: 5,
                                            text: 'Save',
                                            listeners: {
                                                click: 'save'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            itemId: 'cancelButton',
                                            margin: 5,
                                            text: 'Cancel',
                                            listeners: {
                                                click: 'cancelEdit'
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            text: 'Adicionar',
                            listeners: {
                                click: 'add'
                            }
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            text: 'Editar',
                            bind: {
                                hidden: '{!record}'
                            },
                            listeners: {
                                click: 'edit'
                            }
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            text: 'Remover',
                            bind: {
                                hidden: '{!record}'
                            },
                            listeners: {
                                click: 'remove'
                            }
                        }
                    ]
                }
            ]
        }
    ]

});