/*
 * File: app/controller/MainController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TaskList.controller.MainController', {
    extend: 'Ext.app.Controller',

    init: function(application) {
          this.control({
           "loginform": {
             login: this.onLogin
            }
          });
    },

    onLogin: function(loginDialog, loginForm, loginCredentials) {
         var me = this;

           // authenticate
           Ext.Ajax.request({
            url: 'resources/cred.json',
            params: {
             username: loginCredentials.username,
             password: loginCredentials.password
            },
            success: function(response) {

             // convert text response to javascript object
             var data = Ext.decode(response.responseText);

             // if server response contains "firstName" node, then success!
             if (data.firstName == 'admin') {
              // instantiate user info in global scope for easy referencing
              TaskList.User = Ext.create("TaskList.user.Profile", {
                                firstName: data.firstName,
                                lastName: data.lastName,
                                roles: data.roles
              });

              // destroy login dialog
              loginDialog.destroy();


              Ext.Msg.alert("Logado com Sucesso",
                        Ext.String.format("Bem Vindo {0} {1}",
                                  TaskList.User.getFirstName(),
                                  TaskList.User.getLastName())
              );

              // load main UI
              //Ext.create("TaskList.view.Viewport");
              Ext.getCmp('edit').enable();
              Ext.getCmp('remove').enable();
              Ext.getCmp('add').disable();
              Ext.getCmp('checkVerificado').enable();


          } else { // login failed
            Ext.Msg.alert("Credenciais Inválidas",
                          "Você deve digitar credenciais válidas",
                          function() {
                       loginForm.getForm().reset();
                          }
            );
          }
         }
        });
    }

});
